steps:
  - id: 'terrascan'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |-
      curl -L https://github.com/tenable/terrascan/releases/download/v1.19.9/terrascan_1.19.9_Linux_x86_64.tar.gz > terrascan.tar.gz
      tar -xf terrascan.tar.gz terrascan
      install terrascan /usr/local/bin
      cd org01/env/${_LOCATION}
      terrascan init -l debug
      terrascan scan
      echo Last error code: $?
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.11.2'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      ./run-all.sh init ${_LOCATION}
  - id: 'terraform validate'
    name: 'hashicorp/terraform:1.11.2'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      ./run-all.sh validate ${_LOCATION}
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.11.2'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      ./run-all.sh plan ${_LOCATION}
  - id: 'terraform apply/destroy'
    name: 'hashicorp/terraform:1.11.2'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      ./run-all.sh ${_COMMAND} ${_LOCATION}
options:
  logging: CLOUD_LOGGING_ONLY
